Second Commit

diff --git a/.github/workflows/action-terraform-verify.yml b/.github/workflows/action-terraform-verify.yml
--- a/.github/workflows/action-terraform-verify.yml
+++ b/.github/workflows/action-terraform-verify.yml
@@ -1,52 +1,51 @@
-name: Validate terraform fmt
+name: Validate Terraform Formatting and Syntax
+ 
 on:
   pull_request:
     branches:
       - main
       - master
-
+ 
 permissions:
   id-token: write
   contents: read
-
+ 
 jobs:
-  validate:
+  validate_formatting_syntax:
     runs-on: ubuntu-latest
-    name: terraform fmt check
+    name: Validate Terraform Formatting and Syntax
     outputs:
       CHECK_STATUS: "${{ env.CHECK_STATUS }}"
     steps:
-      - uses: actions/checkout@v3
+      - name: Checkout code
+        uses: actions/checkout@v3
         with:
           fetch-depth: 2
-      - name: Fetch changed files
-        id: pr_files
-        uses: jitterbit/get-changed-files@v1
-        with:
-          format: "space-delimited"
-      - name: Configure terraform
+ 
+      - name: Configure Terraform
         uses: hashicorp/setup-terraform@v2
         with:
           terraform_version: 1.2.4
-      - name: Validate terraform fmt (added_modified)
+ 
+      - name: Validate Terraform Formatting and Syntax
         run: |
           set +e
-
+ 
           echo "CHECK_STATUS=0" >> $GITHUB_ENV
-
-          for changed_file in ${{ steps.pr_files.outputs.added_modified }}; do
-            echo "Checking terraform fmt on ${changed_file}..."
-
-            if [[ $changed_file == *.tf ]]; then
-              terraform fmt -check $changed_file
-              FMT_STATUS=$(echo $?)
-
-              if [[ $FMT_STATUS -ne 0 ]]; then
-                echo "❌ terraform fmt failed - ${changed_file}" >> $GITHUB_STEP_SUMMARY
-                echo "CHECK_STATUS=1" >> $GITHUB_ENV
-              fi
-            fi
-          done
+ 
+          # Run terraform fmt and validate commands
+          terraform fmt -check -recursive
+          FMT_STATUS=$?
+ 
+          terraform validate
+          VALIDATE_STATUS=$?
+ 
+          # Set CHECK_STATUS based on the status of formatting and validation
+          if [[ $FMT_STATUS -ne 0 || $VALIDATE_STATUS -ne 0 ]]; then
+            echo "❌ Terraform formatting or syntax validation failed" >> $GITHUB_STEP_SUMMARY
+            echo "CHECK_STATUS=1" >> $GITHUB_ENV
+          fi
+ 
       - name: Process check
         if: always()
         run: exit $CHECK_STATUS
